pages_build_output_dir = "./dist"
compatibility_date = "2026-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "db"
database_name = "xxxxxx"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
remote = true